---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: webapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
  namespace: webapp
rules:
  - apiGroups: [""]
    resources:
      ["pods", "services", "secrets", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "create", "delete", "patch", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "create", "delete", "patch", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
  namespace: webapp
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: webapp
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: jenkinstoken
  namespace: webapp
  annotations:
    kubernetes.io/service-account.name: jenkins # The service account name
